Repository cBioPortal/oncotree, pull requests merged in 2018-08, with the labels that each got.

#139 add back older oncotree versions to dropdown
  web/src/main/resources/static/index.html
  web/src/main/resources/static/js/main.js
  web/src/main/resources/static/js/tree.js
Labels: enhancement, frontend

#140 update news for August 1 release
  docs/News.md
Labels: data

#136 Enable jar build profile and spring boot launch
  core/src/main/java/org/mskcc/oncotree/utils/TumorTypesUtil.java
  web/pom.xml
  web/src/main/java/org/mskcc/oncotree/api/TumorTypesApi.java
Labels: enhancement

#138 integration tests to ensure oncotree release doesn't break downstream…
  integration-tests/default_oncotree_file.txt
  integration-tests/test-oncotree-dependent-tools.sh
  integration-tests/verify_oncotree_code_converter.py
Labels: integration-tests

#141 correct bug in integration test filename paths
  integration-tests/test-oncotree-dependent-tools.sh
  integration-tests/verify_oncotree_code_converter_output.py
Labels: bug, integration-tests
