Repository cBioPortal/oncotree, pull requests merged in 2018-04, with the labels that each got.

#104 Cache objects were being modified when they shouldn't
  core/src/main/java/org/mskcc/oncotree/model/Links.java
  core/src/main/java/org/mskcc/oncotree/model/MainType.java
  core/src/main/java/org/mskcc/oncotree/model/TumorType.java
  core/src/main/java/org/mskcc/oncotree/utils/CacheUtil.java
  web/src/main/java/org/mskcc/oncotree/api/GlobalControllerExceptionHandler.java
Labels: bug, service

#105 Make deep copy of children
  core/src/main/java/org/mskcc/oncotree/model/TumorType.java
Labels: bug, service

#102 Code cleanup and cache refreshing
  core/pom.xml
  core/src/main/java/org/mskcc/oncotree/error/InvalidQueryException.java
  core/src/main/java/org/mskcc/oncotree/model/ChildrenListResp.java
  core/src/main/java/org/mskcc/oncotree/model/ChildrenListRespData.java
  core/src/main/java/org/mskcc/oncotree/model/CreateTumorTypeResp.java
  core/src/main/java/org/mskcc/oncotree/model/CreateTumorTypeRespData.java
  core/src/main/java/org/mskcc/oncotree/model/DeleteTumorTypeResp.java
  core/src/main/java/org/mskcc/oncotree/model/InlineResponse200.java
  core/src/main/java/org/mskcc/oncotree/model/Link.java
  core/src/main/java/org/mskcc/oncotree/model/Links.java
  core/src/main/java/org/mskcc/oncotree/model/MainType.java
  core/src/main/java/org/mskcc/oncotree/model/MainTypeResp.java
  core/src/main/java/org/mskcc/oncotree/model/MainTypesResp.java
  core/src/main/java/org/mskcc/oncotree/model/Meta.java
  core/src/main/java/org/mskcc/oncotree/model/SearchTumorTypesPostResp.java
  core/src/main/java/org/mskcc/oncotree/model/SearchTumorTypesResp.java
  core/src/main/java/org/mskcc/oncotree/model/TumorType.java
  core/src/main/java/org/mskcc/oncotree/model/TumorTypeQuery.java
  core/src/main/java/org/mskcc/oncotree/model/TumorTypeResp.java
  core/src/main/java/org/mskcc/oncotree/model/UpdateTumorTypeResp.java
  core/src/main/java/org/mskcc/oncotree/model/User.java
  core/src/main/java/org/mskcc/oncotree/model/Version.java
  core/src/main/java/org/mskcc/oncotree/model/VersionsResp.java
  core/src/main/java/org/mskcc/oncotree/topbraid/TopBraidException.java
  core/src/main/java/org/mskcc/oncotree/utils/CacheUtil.java
  core/src/main/java/org/mskcc/oncotree/utils/MainTypesUtil.java
  core/src/main/java/org/mskcc/oncotree/utils/TumorTypesUtil.java
  core/src/test/java/org/mskcc/oncotree/utils/MainTypesUtilTest.java
  core/src/test/java/org/mskcc/oncotree/utils/OncotreeTestConfig.java
  core/src/test/java/org/mskcc/oncotree/utils/TumorTypesUtilTest.java
  pom.xml
  web/src/main/java/org/mskcc/oncotree/OncotreeApplication.java
  web/src/main/java/org/mskcc/oncotree/api/ApiException.java
  web/src/main/java/org/mskcc/oncotree/api/ApiOriginFilter.java
  web/src/main/java/org/mskcc/oncotree/api/ApiResponseMessage.java
  web/src/main/java/org/mskcc/oncotree/api/GlobalControllerExceptionHandler.java
  web/src/main/java/org/mskcc/oncotree/api/MainTypesApi.java
  web/src/main/java/org/mskcc/oncotree/api/NotFoundException.java
  web/src/main/java/org/mskcc/oncotree/api/OncotreeMappingsApi.java
  web/src/main/java/org/mskcc/oncotree/api/RootApi.java
  web/src/main/java/org/mskcc/oncotree/api/TumorTypesApi.java
  web/src/main/java/org/mskcc/oncotree/api/TumorTypesTxtApi.java
  web/src/main/java/org/mskcc/oncotree/api/VersionsApi.java
  web/src/main/resources/static/js/main.js
  web/src/main/resources/static/js/oncotree-mapping.js
  web/src/main/resources/static/js/tree.js
Labels: api, enhancement, frontend, service, test

#106 Throw Exceptions when Empty Response Returned
  core/src/main/java/org/mskcc/oncotree/crosswalk/CrosswalkRepository.java
  core/src/main/java/org/mskcc/oncotree/error/OncotreeMappingsNotFound.java
  core/src/main/java/org/mskcc/oncotree/error/UnexpectedCrosswalkResponseException.java
  web/src/main/java/org/mskcc/oncotree/api/GlobalControllerExceptionHandler.java
  web/src/main/java/org/mskcc/oncotree/api/OncotreeMappingsApi.java
  web/src/main/resources/static/js/oncotree-mapping.js
Labels: api, enhancement

#107 fix tree not displaying mainType
  web/src/main/resources/static/js/tree.js
Labels: bug, frontend

#109 Update resource_uri_to_oncocode_mapping.txt
  docs/resource_uri_to_oncocode_mapping.txt
Labels: data

#110 Removed large margin on right side of API frame
  web/src/main/resources/static/js/news.js
Labels: bug, frontend

#114 remote id from swagger doc tumortype search choices
  web/src/main/java/org/mskcc/oncotree/api/TumorTypesApi.java
Labels: api, bug

#112 Update News.md
  docs/News.md
Labels: enhancement, frontend

#115 Update News.md
  docs/News.md
Labels: data

#113 Maint 0.0.1
  core/pom.xml
  core/src/main/java/org/mskcc/oncotree/model/ChildrenListResp.java
  core/src/main/java/org/mskcc/oncotree/model/ChildrenListRespData.java
  core/src/main/java/org/mskcc/oncotree/model/CreateTumorTypeResp.java
  core/src/main/java/org/mskcc/oncotree/model/CreateTumorTypeRespData.java
  core/src/main/java/org/mskcc/oncotree/model/DeleteTumorTypeResp.java
  core/src/main/java/org/mskcc/oncotree/model/MainTypeResp.java
  core/src/main/java/org/mskcc/oncotree/model/TumorTypeResp.java
  core/src/main/java/org/mskcc/oncotree/model/UpdateTumorTypeResp.java
  core/src/main/java/org/mskcc/oncotree/model/User.java
  core/src/main/java/org/mskcc/oncotree/model/Version.java
  core/src/main/java/org/mskcc/oncotree/topbraid/TopBraidException.java
  core/src/main/java/org/mskcc/oncotree/utils/CacheUtil.java
  core/src/main/java/org/mskcc/oncotree/utils/TumorTypesUtil.java
  web/src/main/java/org/mskcc/oncotree/api/ApiException.java
  web/src/main/java/org/mskcc/oncotree/api/ApiOriginFilter.java
  web/src/main/java/org/mskcc/oncotree/api/ApiResponseMessage.java
  web/src/main/java/org/mskcc/oncotree/api/MainTypesApi.java
  web/src/main/java/org/mskcc/oncotree/api/NotFoundException.java
  web/src/main/java/org/mskcc/oncotree/api/RootApi.java
  web/src/main/java/org/mskcc/oncotree/api/TumorTypesApi.java
  web/src/main/java/org/mskcc/oncotree/api/TumorTypesTxtApi.java
  web/src/main/java/org/mskcc/oncotree/api/VersionsApi.java
  web/src/main/resources/static/index.html
  web/src/main/resources/static/js/news.js
  web/src/main/resources/static/js/oncotree-mapping.js
Labels: api, frontend, service

#117 delete children from API search responses
  core/src/main/java/org/mskcc/oncotree/utils/TumorTypesUtil.java
Labels: service

#116 Add warning about discontinuance directly on swagger page
  web/src/main/java/org/mskcc/oncotree/OncotreeApplication.java
Labels: api
