Repository cBioPortal/oncotree, pull requests merged in 2018-07, with the labels that each got.

#132 add download section to mappings tab
  web/src/main/resources/static/css/style.css
  web/src/main/resources/static/download/oncotree_2018_06_15_ICD-O-3_map.txt
  web/src/main/resources/static/index.html
Labels: data, enhancement, frontend

#133 VersionUtil changed to go through CacheUtil instead of directly querying TopBraid
  core/src/main/java/org/mskcc/oncotree/crosswalk/MSKConceptCache.java
  core/src/main/java/org/mskcc/oncotree/utils/CacheUtil.java
  core/src/main/java/org/mskcc/oncotree/utils/VersionUtil.java
  core/src/test/java/org/mskcc/oncotree/utils/CacheUtilTest.java
  core/src/test/java/org/mskcc/oncotree/utils/OncotreeTestConfig.java
  core/src/test/java/org/mskcc/oncotree/utils/VersionUtilTest.java
Labels: bug, enhancement

#135 drop IDCO download section
  web/src/main/resources/static/download/oncotree_2018_06_15_ICD-O-3_map.txt
  web/src/main/resources/static/index.html
Labels: frontend

#137 disable/hide oncotree-mappings tab
  web/src/main/resources/static/index.html
Labels: frontend
