Repository cBioPortal/oncotree, pull requests merged in 2018-05, with the labels that each got.

#119 Update News.md
  docs/News.md
Labels: data

#121 Never null the cache
  core/src/main/java/org/mskcc/oncotree/utils/CacheUtil.java
  core/src/main/java/org/mskcc/oncotree/utils/FailedCacheRefreshException.java
  core/src/test/java/org/mskcc/oncotree/utils/OncotreeTestConfig.java
  core/src/test/java/org/mskcc/oncotree/utils/TumorTypesUtilTest.java
  web/src/main/java/org/mskcc/oncotree/api/GlobalControllerExceptionHandler.java
  web/src/main/resources/application.properties-EXAMPLE
Labels: enhancement, repository

#122 never null the cache
  core/src/main/java/org/mskcc/oncotree/utils/CacheUtil.java
  core/src/main/java/org/mskcc/oncotree/utils/FailedCacheRefreshException.java
  core/src/test/java/org/mskcc/oncotree/utils/OncotreeTestConfig.java
  core/src/test/java/org/mskcc/oncotree/utils/TumorTypesUtilTest.java
  web/src/main/java/org/mskcc/oncotree/api/GlobalControllerExceptionHandler.java
  web/src/main/resources/application.properties-EXAMPLE
Labels: enhancement, repository

#123 Remove broken/unneeded exception handler link
  web/src/main/java/org/mskcc/oncotree/api/GlobalControllerExceptionHandler.java
Labels: api, bug

#125 Cleaned up improper static method interactions
  core/src/main/java/org/mskcc/oncotree/crosswalk/MSKConceptCache.java
  core/src/main/java/org/mskcc/oncotree/utils/CacheUtil.java
  core/src/main/java/org/mskcc/oncotree/utils/MainTypesUtil.java
  core/src/main/java/org/mskcc/oncotree/utils/TumorTypesUtil.java
  core/src/main/java/org/mskcc/oncotree/utils/VersionUtil.java
  core/src/test/java/org/mskcc/oncotree/utils/OncotreeTestConfig.java
  core/src/test/java/org/mskcc/oncotree/utils/TumorTypesUtilTest.java
  web/src/main/java/org/mskcc/oncotree/api/MainTypesApi.java
  web/src/main/java/org/mskcc/oncotree/api/RootApi.java
  web/src/main/java/org/mskcc/oncotree/api/TumorTypesApi.java
  web/src/main/java/org/mskcc/oncotree/api/TumorTypesTxtApi.java
  web/src/main/java/org/mskcc/oncotree/api/VersionsApi.java
Labels: bug, enhancement
