Repository cBioPortal/oncotree, pull requests merged in 2019-03, with the labels that each got.

#156 Update News.md
  docs/News.md
Labels: data

#160 Unit/Integration Testing
  integration-tests/default_oncotree_file_converted.txt
  integration-tests/test-oncotree-dependent-tools.sh
  scripts/cross_version_oncotree_translator.py
  scripts/test/test_cross_version_oncotree_translator.py
Labels: integration-tests, test

#159 develop new feature to open tree to a search term from url
  core/src/main/java/org/mskcc/oncotree/crosswalk/CrosswalkRepository.java
  web/src/main/resources/application.properties-EXAMPLE
  web/src/main/resources/static/js/main.js
  web/src/main/resources/static/js/tree.js
Labels: enhancement, frontend

#161 Deal with PTCL showing up in its own history
  core/src/main/java/org/mskcc/oncotree/utils/TumorTypesUtil.java
  web/src/main/resources/static/js/tree.js
Labels: api, enhancement, frontend

#162 reinstate mappings tab
  web/src/main/resources/static/index.html
  web/src/main/resources/static/js/main.js
Labels: enhancement, frontend

#163 Fixed front end pop up bug which removed words in parentheses
  web/src/main/resources/static/js/tree.js
Labels: bug, frontend

#164 Add log url
  scripts/cross_version_oncotree_translator.py
Labels: do not merge

#166 bug fixes
  scripts/cross_version_oncotree_translator.py
Labels: scripts

#167 Oncotree mapper dev
  scripts/cross_version_oncotree_translator.py
Labels: scripts

#169 Display oncotree version converter documentation from github markdown
  web/src/main/resources/static/index.html
  web/src/main/resources/static/js/load-markdown.js
  web/src/main/resources/static/js/news.js
Labels: do not merge, enhancement, frontend

#170 Oncotree mapper dev
  docs/OncoTree-Mapping-Tool.md
  scripts/oncotree_to_oncotree.py
Labels: scripts

#171 Enhanced history relationships and mapping tool
  .gitignore
  README.md
  core/src/main/java/org/mskcc/oncotree/crosswalk/CrosswalkRepository.java
  core/src/main/java/org/mskcc/oncotree/crosswalk/MSKConcept.java
  core/src/main/java/org/mskcc/oncotree/crosswalk/MSKConceptCache.java
  core/src/main/java/org/mskcc/oncotree/model/TumorType.java
  core/src/main/java/org/mskcc/oncotree/topbraid/OncoTreeNode.java
  core/src/main/java/org/mskcc/oncotree/topbraid/OncoTreeRepository.java
  core/src/main/java/org/mskcc/oncotree/topbraid/OncoTreeVersionRepository.java
  core/src/main/java/org/mskcc/oncotree/utils/CacheUtil.java
  core/src/main/java/org/mskcc/oncotree/utils/TumorTypesUtil.java
  core/src/test/java/org/mskcc/oncotree/utils/CacheUtilTest.java
  core/src/test/java/org/mskcc/oncotree/utils/OncotreeTestConfig.java
  core/src/test/java/org/mskcc/oncotree/utils/TumorTypesUtilTest.java
  docs/OncoTree-Mapping-Tool.md
  docs/images/example_1.png
  integration-tests/default_oncotree_file_converted.txt
  integration-tests/test-oncotree-dependent-tools.sh
  pom.xml
  scripts/oncotree_to_oncotree.py
  scripts/pom.xml
  scripts/test/__init__.py
  scripts/test/test_oncotree_to_oncotree.py
  web/pom.xml
  web/src/main/resources/application.properties-EXAMPLE
  web/src/main/resources/static/index.html
  web/src/main/resources/static/js/load-markdown.js
  web/src/main/resources/static/js/main.js
  web/src/main/resources/static/js/news.js
  web/src/main/resources/static/js/tree.js
Labels: api, frontend, scripts, test

#172 Update Oncotree-Mapping-Tool.md
  docs/OncoTree-Mapping-Tool.md
Labels: scripts

#173 Tab Content Bug
  web/src/main/resources/static/index.html
Labels: bug

#175 Fixing integration tests
  integration-tests/default_oncotree_file_converted.txt
  integration-tests/test-oncotree-dependent-tools.sh
Labels: integration-tests

#174 Version menu now is a Bootstrap menu …
  web/src/main/resources/static/css/bootstrap.min.css
  web/src/main/resources/static/css/style.css
  web/src/main/resources/static/index.html
  web/src/main/resources/static/js/bootstrap.min.js
  web/src/main/resources/static/js/main.js
  web/src/main/resources/static/js/popper.min.js
Labels: frontend

#176 seperate single direct mapping w/ more granular choices from those w/o
  scripts/oncotree_to_oncotree.py
Labels: scripts

#180 Submenu closes when menu gets closed (or really when it is opened)
  web/src/main/resources/static/js/main.js
Labels: frontend

#182 adjust style for version selector elements
  web/src/main/resources/static/css/style.css
  web/src/main/resources/static/index.html
Labels: frontend
